# utils.py

color_map = {"Li": "pink",
             "B": "sienna",
             "Mg": "lawngreen",
             "Al": "silver",
             "Ti": "gray",
             "V": "yellow",
             "Cr": "red",
             "Mn": "purple",
             "Fe": "black",
             "Co": "blue",
             "Ni": "green",
             "Cu": "peru",
             "Zn": "deepskyblue",
             "Y": "olive",
             "Zr": "orangered",
             "Nb": "darkviolet",
             "Mo": "orange",
             "Ag": "silver",
             "Sn": "slategray",
             "Hf": "deepskyblue",
             "Ta": "darkgoldenrod",
             "W": "gold",
             "Re": "mediumorchid",
             }
